[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1.5.0"
regex = "1.11.1"


[lib]
name = "aoc"
path = "src/lib/lib.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"
